"""empty message

Revision ID: 6e58e38124dd
Revises: f278fd4e0a09
Create Date: 2019-11-14 20:12:53.471430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e58e38124dd'
down_revision = 'f278fd4e0a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'email')
    op.drop_column('Artist', 'email')
    # ### end Alembic commands ###
